# Cross Validation :

Cross-validation is a robust resampling technique in machine learning used to evaluate model performance and prevent overfitting by training and testing a model on multiple, rotating subsets (folds) of the data.

a robust resampling technique in machine learning used to evaluate model performance and prevent overfitting by training and testing a model on multiple, rotating subsets (folds) of the data. It ensures every data point acts as both training and validation data, providing a more reliable estimate of how the model generalizes to unseen data than a single train-test split.

it validates the model efficiency by training it on the subset of input data and testing on previously unseen subset of input data.

Types of cross validataion : GFG


In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
dataset = pd.read_csv("Placement _1.csv")
dataset.head()

,Student_ID,CGPA,Internships,Placed,Salary (INR LPA)
0,1,7.90,3,Yes,17.63
1,2,7.39,0,Yes,28.37
2,3,8.02,2,Yes,8.95
3,4,8.72,4,Yes,22.59
4,5,7.31,2,Yes,19.67


Seperating Data : Cgpa and Salary

In [27]:
x = dataset[["CGPA"]]
y = dataset["Salary (INR LPA)"]

In [28]:
# making small dataset for demo of demonstrating :

new_data = dataset.head(10)

x_new = new_data[["CGPA"]]
y_new = new_data.iloc[:,:-1]

# Cross Validation : 

In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
from sklearn.model_selection import cross_val_score

In [44]:
p = cross_val_score(LinearRegression(),x,y,cv=KFold(n_splits= 10))

In [45]:
p.sort()
p*100

array([-3.18267751, -0.90114364, -0.73465703, -0.71723346, -0.25888452,
       -0.1593475 , -0.00601068,  0.28536772,  0.70121683,  0.82250219])

# LeaveOneOut :

In [32]:
from sklearn.model_selection import LeaveOneOut

In [33]:
lo = LeaveOneOut()

for train , test in lo.split(x_new,y_new) :
    print(train,test)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


# LeavePOut :

In [34]:
from sklearn.model_selection import LeavePOut

In [35]:
lp = LeavePOut(p=3)  # p ki value k hisab se split hoga
 
for train , test in lp.split(x_new,y_new) :
    print(train,test)

[3 4 5 6 7 8 9] [0 1 2]
[2 4 5 6 7 8 9] [0 1 3]
[2 3 5 6 7 8 9] [0 1 4]
[2 3 4 6 7 8 9] [0 1 5]
[2 3 4 5 7 8 9] [0 1 6]
[2 3 4 5 6 8 9] [0 1 7]
[2 3 4 5 6 7 9] [0 1 8]
[2 3 4 5 6 7 8] [0 1 9]
[1 4 5 6 7 8 9] [0 2 3]
[1 3 5 6 7 8 9] [0 2 4]
[1 3 4 6 7 8 9] [0 2 5]
[1 3 4 5 7 8 9] [0 2 6]
[1 3 4 5 6 8 9] [0 2 7]
[1 3 4 5 6 7 9] [0 2 8]
[1 3 4 5 6 7 8] [0 2 9]
[1 2 5 6 7 8 9] [0 3 4]
[1 2 4 6 7 8 9] [0 3 5]
[1 2 4 5 7 8 9] [0 3 6]
[1 2 4 5 6 8 9] [0 3 7]
[1 2 4 5 6 7 9] [0 3 8]
[1 2 4 5 6 7 8] [0 3 9]
[1 2 3 6 7 8 9] [0 4 5]
[1 2 3 5 7 8 9] [0 4 6]
[1 2 3 5 6 8 9] [0 4 7]
[1 2 3 5 6 7 9] [0 4 8]
[1 2 3 5 6 7 8] [0 4 9]
[1 2 3 4 7 8 9] [0 5 6]
[1 2 3 4 6 8 9] [0 5 7]
[1 2 3 4 6 7 9] [0 5 8]
[1 2 3 4 6 7 8] [0 5 9]
[1 2 3 4 5 8 9] [0 6 7]
[1 2 3 4 5 7 9] [0 6 8]
[1 2 3 4 5 7 8] [0 6 9]
[1 2 3 4 5 6 9] [0 7 8]
[1 2 3 4 5 6 8] [0 7 9]
[1 2 3 4 5 6 7] [0 8 9]
[0 4 5 6 7 8 9] [1 2 3]
[0 3 5 6 7 8 9] [1 2 4]
[0 3 4 6 7 8 9] [1 2 5]
[0 3 4 5 7 8 9] [1 2 6]
[0 3 4 5 6 8 9] [1 2 7]
[0 3 4 5 6 7 9] 

# KFold :

uses for both regression and classificcation 

In [36]:
from sklearn.model_selection import KFold

In [37]:
kf = KFold(n_splits=5) # n_splits : kine folds or subparts banana chahte hai
for train , test in kf.split(x_new,y_new) :
    print(train,test)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


# SratifiedFold

only uses for classification analysis

In [38]:
from sklearn.model_selection import StratifiedKFold

In [39]:
# skf = StratifiedKFold(n_splits=5)  

# for train , test in skf.split(x_new,y_new) :
#     print(train,test)